### ISSUE TITLE
trying decode small webp image using simplewebp.

### ISSUE THREAD

**Issue by kazuhiko-shutoh** [MikuAuahDark/simplewebp#1]
Dear MikuAuahDark-san
Hi, I'm testing your simplewebp.h decoder. i got segv in simplewebp__yuv2rgb_plain() . It looks failed obtain image width and height, than segv in decode section.(Attached webp pic and bulk data,)
It saved using GIMP default parameters... If you have spare time, comment plz. 
[tmp.zip](https://github.com/user-attachments/files/16516705/tmp.zip)
best regards,
ミク様。お忙しいところすみませんが、コメントありましたら宜しくお願い致します。

**Comment by MikuAuahDark** [comment]
Hello.

I tested the attached image (not the header file) and I got segv in different part of the file. After I fixed it, the decoding works as intended.

Please let me know if it's not the case.

**Comment by kazuhiko-shutoh** [comment]
Thanks for quick hot fix. Well, Now i back in  evaluate simplewebp again,
After simple_webp_load and decode, finally must call simplewebp_unload() ne?
thanks.

**Comment by MikuAuahDark** [comment]
Yes. `simplewebp_unload(swebp)` needs to be called to free the `simplewebp*` pointer.
